#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '⭐⭐⭐⭐⭐ Running Prettier Check ⭐⭐⭐⭐⭐'

# Check Prettier standards
npm run check-format ||
(
  echo '⛔⛔⛔⛔⛔ Prettier Check Failed ⛔⛔⛔⛔⛔
        👉👉👉 Run "npm run format" => "git add ." => try again... 👈👈👈';
  false;
)

echo '📐📐📐📐📐 Running ESLint Check 📐📐📐📐📐'

# Check ESLint Standards
npm run check-lint ||
(
  echo '⛔⛔⛔⛔⛔ ESLint Check Failed ⛔⛔⛔⛔⛔
        👉👉👉 Make the required changes listed above => try again... 👈👈👈'
  false; 
)

echo '🧾🧾🧾🧾🧾 Running Type Check 🧾🧾🧾🧾🧾'

# Check tsconfig standards
npm run check-types ||
(
  echo '⛔⛔⛔⛔⛔ Type Check Failed ⛔⛔⛔⛔⛔
        👉👉👉 Make the changes required above => try again... 👈👈👈'
  false;
)

# Check if build is valid
echo '🛠️🛠️🛠️🛠️🛠️ Running Build Check 🛠️🛠️🛠️🛠️🛠️'

npm run build ||
(
  echo '⛔⛔⛔⛔⛔ NextJS Build Failed ⛔⛔⛔⛔⛔
        👉👉👉 View the errors above to see why => try again... 👈👈👈'
  false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅✅ Success!!! ✅✅✅✅✅'